name: HarvesterHoes
version: '${project.version}'
main: me.tzmo.harvesterhoes.HarvesterHoes
api-version: 1.19
authors: [ Tzmo ]
depend: [ NBTAPI, ShopGUIPlus, Vault ]
description: A simple Harvester Hoe plugin with multipliers that can be upgradable.

commands:
    harvesterhoe:
        description: Harvester Hoe base command
        permission: harvesterhoes.basecommand
    autosell:
        description: Toggle Auto Sell mode for the Harvester Hoe
        permission: harvesterhoes.autosell

permissions:
    harvesterhoes.autosell: { description: Toggle Auto Sell mode for the Harvester Hoe, default: true }
    harvesterhoes.basecommand: { description: Harvester Hoe base command, default: op }
    harvesterhoes.give: { description: Give a player a Harvester Hoe, default: op }
    harvesterhoes.reload: { description: Reloads the config, default: op }